### ISSUE TITLE
Issues on install

### ISSUE THREAD

**Issue by robmarkcole** [geotiffjs/cog-explorer#13]
Hi
I've hit a couple of errors when following the README, appears some dependencies are deprecated:

```
Robins-MacBook:cog-explorer robincole$ npm install
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> fsevents@1.2.4 install /Users/robincole/Documents/Github/cog-explorer/node_modules/fsevents
> node install

[fsevents] Success: "/Users/robincole/Documents/Github/cog-explorer/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN l8app@1.0.0 No repository field.

added 1435 packages from 722 contributors and audited 20138 packages in 45.519s
found 0 vulnerabilities

Robins-MacBook:cog-explorer robincole$ npm run build

> l8app@1.0.0 build /Users/robincole/Documents/Github/cog-explorer
> rm dist/* ; webpack --config webpack.conf.js; cp -R images/ index.html dist/

rm: dist/images: is a directory
/Users/robincole/Documents/Github/cog-explorer/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                          ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/robincole/Documents/Github/cog-explorer/node_modules/webpack-cli/bin/config-yargs.js:89:47)
    at /Users/robincole/Documents/Github/cog-explorer/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/Users/robincole/Documents/Github/cog-explorer/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
Robins-MacBook:cog-explorer robincole$
```

**Comment by constantinius** [comment]
Hi @robmarkcole 

Thanks for reporting the issue, I'll have to investigate this
